<?php

class FII_RESTRICT_CONTENT extends FII_BASE {

  function __construct(){

    add_action( 'init', array( $this, 'init' ) );

    add_action( 'template_redirect', array( $this, 'private_page_redirect' ) );

    add_filter( 'wp_get_nav_menu_items', array( $this, 'nav_items') );

    add_filter( 'wpmem_restricted_msg', array( $this, 'restricted_msg' ), 10, 2 );

    add_action( 'wp_ajax_fii_add_caps_subscriber', array( $this, 'add_capabilities_to_subscriber' ) );

  }

  /**
	 * Retrieves login page url
	 *
	 * @param int $page_id ID of the page.
	 * @return string Custom login-page URL if the plugin method exists, or default login-page URL.
	 */
  private function get_login_page_url( $page_id ){
    $redirect_url = get_permalink( $page_id );

    if( function_exists('wpmem_login_url') && $mem_login_url = wpmem_login_url() ){
      return "$mem_login_url?redirect_to=".urlencode( $redirect_url );
    } else {
      return wp_login_url( $redirect_url );
    }

  }

  /**
   * Block dashboard access for subscribers
   */
  function init(){
    if( is_admin() && current_user_can( 'subscriber' ) && !( defined( 'DOING_AJAX' ) && DOING_AJAX ) ){
      wp_redirect( home_url() );
      exit;
    }
  }

  /**
   * Redirects logged-out users to login-page if they access private page on the frontend
   */
  function private_page_redirect(){
    $queried_object = get_queried_object();

    if( isset( $queried_object->post_status ) && isset( $queried_object->post_type ) &&
      'private' === $queried_object->post_status && 'page' === $queried_object->post_type && ! is_user_logged_in() ){
      wp_safe_redirect( $this->get_login_page_url( $queried_object->ID ) );

      exit;
    }

  }

  /**
   * Add redirect_to query-param to all nav_links that have navigation label set to login
   */
  function nav_items( $items ){

    if( is_admin() ){
      return $items;
    }

    global $wp;

    foreach( $items as $item ){
      if( !empty( $item->post_title ) && 'login' == strtolower( $item->post_title ) ){
        $item->url .= '?redirect_to='.urlencode( esc_url( home_url( $wp->request ) ) );
      }
    }

    return $items;

  }

  /**
   * Modify restricted-message layout that's generated by the plugin
   */
  function restricted_msg( $full_html, $msg ){
    return '<div class="wtp-wpmem-restricted-msg">
              <h4>'.$msg.'</h4>
            </div>';
  }


  /**
   * Add capabilities to subscriber role
   */
  function add_capabilities_to_subscriber(){
    $role = get_role( 'subscriber' );
    print_r( $role );
    $role->add_cap( 'read_private_pages' );
    wp_die();
  }

}

FII_RESTRICT_CONTENT::getInstance();
